/**
 * Mapeamento lucide-react → slugs IconJar (outline), validados contra o manifest.
 * Github/Figma ficam em lucide-react (logos de plataforma).
 * Para ícones sem match direto, usamos o mais próximo visualmente.
 */
export const ICON_MAP = {
  Home: 'home-01',
  ArrowRight: 'arrow-right',
  ArrowUp: 'arrow-up',
  ArrowDown: 'arrow-down',
  ArrowLeft: 'arrow-left',
  ChevronRight: 'direction-right',
  ChevronLeft: 'direction-left',
  ChevronDown: 'direction-down',
  ChevronUp: 'direction-up',
  X: 'multiply-circle',
  Plus: 'plus-01',
  Check: 'check-mark-circle',
  Search: 'search-01',
  Mail: 'mail',
  Lock: 'lock',
  User: 'user',
  Users: 'users-02',
  Settings: 'setting',
  Shield: 'shield',
  Heart: 'heart',
  Download: 'download-01',
  Upload: 'file-upload-01',
  Copy: 'copy',
  Trash2: 'trash-01',
  Trash: 'trash-01',
  Pencil: 'pencil',
  Edit: 'edit',
  Edit2: 'edit',
  Eye: 'view',
  EyeOff: 'view-off',
  Bell: 'notification-01',
  Zap: 'flash',
  Sparkles: 'star',
  Star: 'star',
  Sun: 'sun',
  Moon: 'half-moon',
  MoonStar: 'half-moon',
  Info: 'information-circle',
  AlertCircle: 'warning',
  AlertTriangle: 'warning',
  HelpCircle: 'help-01',
  Clock: 'clock-circle',
  History: 'clock-circle',
  Calendar: 'calendar',
  KeyRound: 'smart-key',
  Key: 'smart-key',
  Webhook: 'link',
  Link: 'link',
  ExternalLink: 'link',
  Building2: 'store-01',
  Building: 'store-01',
  Store: 'store-01',
  LogOut: 'logout-01',
  LogIn: 'logout',
  Grid3x3: 'grid-01',
  LayoutGrid: 'grid-01',
  Blocks: 'grid-01',
  Layout: 'grid-01',
  Focus: 'focus',
  Target: 'target',
  Sliders: 'filter-01',
  SlidersHorizontal: 'filter-01',
  Filter: 'filter-01',
  Palette: 'paint-board',
  Type: 'font-size',
  Ruler: 'ruler',
  Package: 'package-01',
  FileJson: 'file-01',
  FileText: 'file-01',
  File: 'file-01',
  ClipboardCheck: 'task-check',
  Clipboard: 'clipboard',
  GitBranch: 'link',
  MousePointer2: 'input-cursor-move',
  MousePointer: 'input-cursor-move',
  Code2: 'file-01',
  Code: 'file-01',
  Terminal: 'file-01',
  Command: 'smart-key',
  Send: 'send',
  Menu: 'menu-line-horizontal',
  MoreHorizontal: 'menu-line-horizontal-01',
  MoreVertical: 'menu-line-vertical-01',
  Box: 'package-01',
  Square: 'plus-rectangle',
  Loader2: 'loading-01',
  Loader: 'loading-01',
  RefreshCw: 'reload',
  Play: 'play',
  Pause: 'pause',
  Link2: 'link',
} as const

export type LucideName = keyof typeof ICON_MAP

export function slugFor(lucideName: string): string {
  return (ICON_MAP as Record<string, string>)[lucideName] ?? 'plus-rectangle'
}
